### ISSUE TITLE
test

### ISSUE THREAD

**Issue by hanyue2020** [jfcg/sorty#1]
![photo_2020-04-17_18-58-33](https://user-images.githubusercontent.com/5828315/79562461-b7eb4b80-80dd-11ea-8925-15006a0beeb1.jpg)
![photo_2020-04-17_18-58-03](https://user-images.githubusercontent.com/5828315/79562464-b9b50f00-80dd-11ea-98aa-9e0fbf61a9f8.jpg)
![photo_2020-04-17_18-58-33](https://user-images.githubusercontent.com/5828315/79562466-ba4da580-80dd-11ea-8f25-b5e82704100d.jpg)

**Comment by jfcg** [comment]
Hi,
It is a very short array to do any meaningful comparison. Also, did you want to test them on already sorted arrays?

**Comment by jfcg** [comment]
Inactive issue
