### ISSUE TITLE
Provide a Slice(interface{}) function

### ISSUE THREAD

**Issue by Alex-duzhichao** [jfcg/sorty#3]
Hello, thanks for the sorty library.
Would  sorty provide a SortInterface(interface{}) funciton, which use reflect to determine the concrete type of parameter?
I think it's very convenient for the callers to call this SortInterface function without care about the concrete type to be sorted.

Thanks.

**Comment by jfcg** [comment]
just added `SortB([][]byte)` and released `v1.1` :)
