### ISSUE TITLE
github.com/jfcg/sorty/v2.SortSlice: nosplit stack over 792 byte limit

### ISSUE THREAD

**Issue by mariotoffia** [jfcg/sorty#6]
Hi and thanks for a really fast and nice library!!

However, I've stubbled into a problem. When I do debug my unit test, it spits out a (compilation??) error and a stack (see parts of it below).

I'm using a Mac M1 and go 1.20.3. 

Steps to reproduce:
1. git clone https://github.com/mariotoffia/goannoy.git
2. cd go annoy & open vs code
3. Click on debug test in `tests/precision_test.go` -> `TestPrecision`.
4. The console outputs the error stack

However, when doing `run test` or do  `go test` in the shell it seems to work. It is just that I cannot debug. Can you give me some pointers where to event start to debug this problem?

Cheers,
 Mario :)

Parts of the error stack:
Starting: /Users/solo/go/bin/dlv dap --listen=127.0.0.1:55316 --log-dest=3 from /Users/solo/progs/github/goannoy/tests
DAP server listening at: 127.0.0.1:55316
Build Error: go test -c -o /Users/solo/progs/github/goannoy/tests/__debug_bin -gcflags all=-N -l .
# github.com/mariotoffia/goannoy/tests.test
github.com/jfcg/sorty/v2.SortSlice: nosplit stack over 792 byte limit
github.com/jfcg/sorty/v2.SortSlice<1>
    grows 336 bytes, calls github.com/jfcg/sorty/v2.sortI4<1>
        grows 176 bytes, calls runtime.gcWriteBarrier<1>
            grows 224 bytes, calls runtime.wbBufFlush<0>
                grows 32 bytes, calls runtime.wbBufFlush<1>
                    grows 32 bytes, calls runtime.cgoCheckWriteBarrier<1>
                        grows 48 bytes, calls runtime.cgoIsGoPointer<1>
                            grows 80 bytes, calls runtime.inHeapOrStack<1>
                                grows 32 bytes, calls runtime.spanOf<1>
                                    grows 48 bytes, calls runtime.arenaIndex<1>
                                    216 bytes over limit
                                    grows 48 bytes, calls runtime.arenaIdx.l2<1>
                                    216 bytes over limit
                                    grows 48 bytes, calls runtime.arenaIdx.l1<1>
                                    216 bytes over limit
                                    grows 48 bytes, calls runtime.arenaIdx.l2<1>
                                    216 bytes over limit
                                    grows 48 bytes, calls runtime.panicIndexU<1>
                                        grows 0 bytes, calls runtime.goPanicIndexU<1>
                                            grows 0 bytes, calls runtime.morestack<0>
                                            216 bytes over limit
                                    grows 48 bytes, calls runtime.panicIndexU<1>
                                        grows 0 bytes, calls runtime.goPanicIndexU<1>
                                            grows 0 bytes, calls runtime.morestack<0>
                                            216 bytes over limit
                                grows 32 bytes, calls runtime.(*mspan).base<1>
                                    grows 0 bytes, calls runtime.morestack<0>
                                    168 bytes over limit
                                grows 32 bytes, calls runtime.(*mSpanStateBox).get<1>
                                    grows 32 bytes, calls runtime/internal/atomic.(*Uint8).Load<1>
                                    200 bytes over limit
                            grows 80 bytes, calls runtime.activeModules<1>
                            136 bytes over limit
                            grows 80 bytes, calls runtime.cgoInRange<1>
                            136 bytes over limit
                            grows 80 bytes, calls runtime.cgoInRange<1>
                            136 bytes over limit
                        grows 48 bytes, calls runtime.cgoIsGoPointer<1>
                            grows 80 bytes, calls runtime.inHeapOrStack<1>
                                grows 32 bytes, calls runtime.spanOf<1>
                                    grows 48 bytes, calls runtime.arenaIndex<1>
                                    216 bytes over limit
                                    grows 48 bytes, calls runtime.arenaIdx.l2<1>
                                    216 bytes over limit
                                    grows 48 bytes, calls runtime.arenaIdx.l1<1>
                                    216 bytes over limit
                                    grows 48 bytes, calls runtime.arenaIdx.l2<1>
                                    216 bytes over limit
                                    grows 48 bytes, calls runtime.panicIndexU<1>
                                        grows 0 bytes, calls runtime.goPanicIndexU<1>
                                            grows 0 bytes, calls runtime.morestack<0>
                                            216 bytes over limit
                                    grows 48 bytes, calls runtime.panicIndexU<1>
                                        grows 0 bytes, calls runtime.goPanicIndexU<1>
                                            grows 0 bytes, calls runtime.morestack<0>
                                            216 bytes over limit
                                grows 32 bytes, calls runtime.(*mspan).base<1>
                                    grows 0 bytes, calls runtime.morestack<0>
                                    168 bytes over limit
                                grows 32 bytes, calls runtime.(*mSpanStateBox).get<1>
                                    grows 32 bytes, calls runtime/internal/atomic.(*Uint8).Load<1>
                                    200 bytes over limit
                            grows 80 bytes, calls runtime.activeModules<1>
                            136 bytes over limit
                            grows 80 bytes, calls runtime.cgoInRange<1>
                            136 bytes over limit
                            grows 80 bytes, calls runtime.cgoInRange<1>
                            136 bytes over limit
                        grows 48 bytes, calls runtime.inPersistentAlloc<1>
                        56 bytes over limit
                        grows 48 bytes, calls runtime.systemstack<0>
                            grows 16 bytes, calls indirect
                                grows 0 bytes, calls runtime.morestack<0>
                                72 bytes over limit
                            grows 16 bytes, calls runtime.abort<0>
                            72 bytes over limit
                            grows 16 bytes, calls gosave_systemstack_switch<20>
                                grows 0 bytes, calls runtime.abort<0>
                                72 bytes over limit
                            grows 16 bytes, calls runtime.save_g<0>
                            72 bytes over limit
.... cont...

**Comment by jfcg** [comment]
I have run into this problem myself. Here is the solution I've found:
- `go test -c -o myTest`
- VS Code > Run and Debug > create a `launch.json` file > "Go" from drop down menu > Go: Launch Package
- Inside `.vscode/launch.json`, update as `"name": "My Test"`, `"mode": "exec"` and `"program": "./myTest"`
- You can give `-test.run regex` argument to `./myTest` to run specific test(s)
- Run and Debug > Green play button will run/debug `./myTest`

I dont really know why compiling the test exec first works.

Cheers..

**Comment by mariotoffia** [comment]
Thanks!! :)

**Comment by s0xzwasd** [comment]
Same issue in GoLand (2023.3.2) and Go 1.21.6 where you cannot change mode to `exec`.

Workaround is to use Attach to Process with `time.Sleep()` but it's requires additional setup and not very straightforward.

```go
package somepackage

import (
	"github.com/mariotoffia/goannoy/builder"
	"testing"
	"time"
)

func Test_IncludeGoAnnoy(t *testing.T) {
	builder := builder.Index[float32, uint32]().
		AngularDistance(255).
		UseMultiWorkerPolicy().
		MmapIndexAllocator().
		Build()
	time.Sleep(time.Second * 15) // set time
	builder.Close() // set breakpoint
}
```

- Set time, run test as usual (not debugging).
- Invoke Run | Attach to Process in the main menu.
- Select a test process (not go test or test2json)

<img width="989" alt="SCR-20240123-idno" src="https://github.com/jfcg/sorty/assets/29286703/af7d8741-5e64-4966-9f84-263a07215518">

@jfcg Could you please take a look? It seems that `-gcflags all=-N -l` + `//go:nosplit` directive causes this issue in 1.19.* and lower: https://github.com/golang/go/issues/54291

https://github.com/golang/go/issues/54291#issuecomment-1316000774

**Comment by jfcg** [comment]
Hi,
For `sorty`'s core use case, removing stack check & preventing preemption (especially at leaf functions) are important for performance. So `go:nosplit` directives need to stay. There is a solution working for VSCode, so maybe you could consider
- adding `"mode": "exec"` launch configuration to GoLand IDE (mid to long term)
- vendoring `sorty` and removing some `go:nosplit`s for getting past your debug compilation errors (short term)

Cheers..
